---
abstract: 'Universal black-box testing'
author:
  - 'Firepear Informatics <firepear@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Firepear-Catechesis
provides:
  Firepear::Catechesis:
    file: lib/Firepear/Catechesis.pm
    version: 1.002
  Firepear::Catechesis::Parser:
    file: lib/Firepear/Catechesis/Parser.pm
    version: 1.000
  Firepear::Catechesis::TAP:
    file: lib/Firepear/Catechesis/TAP.pm
    version: 1.000
  Firepear::Catechesis::Util:
    file: lib/Firepear/Catechesis/Util.pm
    version: 1.000
  Firepear::Catechesis::Verifier:
    file: lib/Firepear/Catechesis/Verifier.pm
    version: 1.000
requires:
  JSON: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.002
